[git_state]
disabled = true

[git_status]
disabled = true

# [git_branch]
# disabled = true

[rust]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
